declare module 'docxtemplater'
declare module 'pizzip/utils/index.js'
declare module '@koumoul/vjsf'
declare module 'angular-expressions'
declare module 'lodash/merge'
declare module '@/firebaseInit'
declare module 'vue-doc-preview'
declare module 'docxtemplater/js/inspect-module.js'
